// <auto-generated />
using FinalProject.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20250804170719_seed-all2")]
    partial class seedall2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Mobile Phone",
                            Name = "Mobile"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Laptop",
                            Name = "Lap"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Accessories",
                            Name = "Acc"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "HardWare",
                            Name = "HW"
                        });
                });

            modelBuilder.Entity("FinalProject.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "The iPhone 11 Pro Max is a high-end smartphone from Apple,featuring a powerful A13 Bionic chip with a hexa-core CPU for smooth and efficient performance.",
                            ImagePath = "/images/iphone-11-pro-max.jpg",
                            Price = 10000m,
                            Quantity = 111,
                            Title = "iPhone 11 Pro Max"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "The iPhone 12 Pro Max, released in 2020, is Apple's flagship smartphone featuring a 6.7-inch Super Retina XDR OLED display and powered by the A14 Bionic chip..",
                            ImagePath = "/images/iphone-12-pro-max.jpg",
                            Price = 20000m,
                            Quantity = 222,
                            Title = "iPhone 12 Pro Max"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "The iPhone 13 Pro Max is Apple's top-tier flagship smartphone released in 2021. It features a large 6.7-inch Super Retina XDR OLED display with ProMotion technology ",
                            ImagePath = "/images/iphone-13-pro-max.jpg",
                            Price = 30000m,
                            Quantity = 333,
                            Title = "iPhone 13 Pro Max"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            Description = "The iPhone 14 Pro Max, released in 2022, features a 6.7-inch Super Retina XDR OLED display with ProMotion technology for a smooth 120Hz refresh rate. It is powered by the A16 Bionic chip, ensuring top-tier performance. The device boasts a triple-camera system with a 48 MP main sensor, enhanced low-light capabilities, and ProRAW/ProRes video recording.",
                            ImagePath = "/images/iphone-14-pro-max.jpg",
                            Price = 40000m,
                            Quantity = 444,
                            Title = "iPhone 14 Pro Max"
                        });
                });

            modelBuilder.Entity("FinalProject.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            Email = "anas.sherif@example.com",
                            FirstName = "Anas",
                            LastName = "Sherif",
                            Password = "pass5678"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "ashraf.fathy@example.com",
                            FirstName = "Ashraf",
                            LastName = "Fathy",
                            Password = "pass9101112"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "salma.mohamed@example.com",
                            FirstName = "Salma",
                            LastName = "Mohamed",
                            Password = "pass13141516"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "mona.mostafa@example.com",
                            FirstName = "Mona",
                            LastName = "Mostafa",
                            Password = "pass17181920"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "emad.shady@example.com",
                            FirstName = "Emad",
                            LastName = "Shady",
                            Password = "pass21222324"
                        },
                        new
                        {
                            UserId = 7,
                            Email = "nancy.kareem@example.com",
                            FirstName = "Nancy",
                            LastName = "Kareem",
                            Password = "pass25262728"
                        },
                        new
                        {
                            UserId = 8,
                            Email = "youssef.mahmoud@example.com",
                            FirstName = "Youssef",
                            LastName = "Mahmoud",
                            Password = "pass29303132"
                        });
                });

            modelBuilder.Entity("FinalProject.Models.Product", b =>
                {
                    b.HasOne("FinalProject.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinalProject.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
